# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='Precio',
        ),
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
