# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20171009_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='update',
        ),
    ]
