# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_remove_libro_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Autor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Editorial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='ISBN',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
    ]
